# Generated by Django 4.1.3 on 2023-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Lifsetyle', 'Lifestyle'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
