# Generated by Django 4.1.3 on 2023-01-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_price_alter_bid_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='minimum_bid',
            field=models.IntegerField(null=True),
        ),
    ]
