# Generated by Django 4.1.3 on 2023-01-15 18:43

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auctions/files/images/default.jpeg', upload_to='auctions/files/images', validators=[auctions.models.Listing.validate_image]),
        ),
    ]
