# Generated by Django 4.1.3 on 2023-01-16 18:26

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='auctions/files/images', validators=[auctions.models.Listing.validate_image]),
        ),
    ]
