# Generated by Django 4.1.3 on 2023-01-17 00:51

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listing-images/default.jpeg', upload_to='auctions/static/auctions/images', validators=[auctions.models.Listing.validate_image]),
        ),
    ]
