# Generated by Django 4.1.3 on 2023-01-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listing_image_personalwatchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalwatchlist',
            old_name='listing',
            new_name='listings',
        ),
    ]
