# Generated by Django 4.1.3 on 2023-01-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_listing_personalwatchlist_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, to='auctions.comment'),
        ),
    ]
